- name: Install
  apt:
    name: shairport-sync
    update_cache: yes

- name: Configure
  template:
    src: shairport-sync.conf
    dest: "{{ shairport_config_file }}"
    mode: "0644"
  notify:
    - restart