- name: restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: postmap
  ansible.builtin.command: postmap {{ postfix_sasl_password_file }}

- name: aliases
  ansible.builtin.command: newaliases
