- name: Check variables
  assert:
    that:
      - grafana.username is defined
      - grafana.password is defined
    quiet: yes

- name: Install
  apt:
    deb: "{{ grafana_agent_deb_url }}"

- name: Configure
  template:
    src: grafana-agent.yaml
    dest: /etc/grafana-agent.yaml
    mode: "0640"
  notify:
    - restart grafana

- name: Enable service
  systemd:
    name: grafana-agent
    enabled: yes
