- name: Check variables
  ansible.builtin.assert:
    that:
      - grafana.username is defined
      - grafana.password is defined
    quiet: yes

- name: Install
  ansible.builtin.apt:
    deb: "{{ grafana_agent_deb_url }}"

- name: Configure defaults
  ansible.builtin.lineinfile:
    path: /etc/default/grafana-agent
    regexp: "^CUSTOM_ARGS="
    line: 'CUSTOM_ARGS="{{ grafana_custom_args }}"'
  notify:
    - restart grafana

- name: Configure service
  ansible.builtin.template:
    src: grafana-agent.yaml
    dest: /etc/grafana-agent.yaml
    mode: "0640"
  notify:
    - restart grafana

- name: Enable service
  ansible.builtin.systemd:
    name: grafana-agent
    enabled: yes
