- hosts: all
  roles:
    - role: backup

  vars:
    backup_keep_days: 90
    backup_dest_dir: /media/disk2/backup
    backup_source_dirs:
      - /boot
      - /etc
      - /home
      - /root
      - /var/lib/docker/volumes
      - /media/disk1/public/documents
      - /media/disk1/public/ebooks
      - /media/disk1/public/music
      - /media/disk1/public/photos
