- hosts: all
  roles:
    - role: kodi

  vars:
    kodi_bin: /usr/local/kodi-nexus/bin/kodi

    kodi_sources:
      - section: games
      - section: music
        sources:
          - name: music
            path: /media/disk1/public/music
      - section: pictures
        sources:
          - name: photos
            path: /media/disk1/public/photos
      - section: programs
      - section: video
        sources:
          - name: video
            path: /media/disk1/public/video

    kodi_advanced_settins:
      # https://kodi.wiki/view/Log_file/Advanced
      log_level: 0
      extra_logging: false
      extra_log_level: 16384 # CEC

    kodi_gui_settings:
      - id: addons.unknownsources
        value: "true"
      - id: audiooutput.audiodevice
        value: ALSA:hdmi:CARD=vc4hdmi0,DEV=0
      - id: audiooutput.passthroughdevice
        value: ALSA:hdmi:CARD=vc4hdmi0,DEV=0
      - id: audiooutput.volumesteps
        value: 50
      - id: locale.audiolanguage
        value: Polish
      - id: locale.subtitlelanguage
        value: Polish
      - id: locale.country
        value: Central Europe
      - id: powermanagement.displaysoff
        value: 5 # 5 minutes
      - id: screensaver.mode
        value: screensaver.xbmc.builtin.dim
      - id: screensaver.time
        value: 1 # 1 minute
      - id: slideshow.staytime
        value: 2
      - id: subtitles.charset
        value: CP1250
      - id: subtitles.height
        value: 32
      - id: subtitles.languages
        value: Polish
      - id: videoplayer.adjustrefreshrate
        value: 2 # on start/stop
      # enable hardware decoder
      - id: videoplayer.useprimedecoder
        value: "true"
      - id: videoplayer.useprimerenderer
        value: 0 # direct to plane
      # enable remote access
      - id: services.webserver
        value: "true"
      - id: services.webserverauthentication
        value: "false"
      - id: services.esallinterfaces
        value: "true"
