- name: Install
  ansible.builtin.apt:
    name: hd-idle

- name: Configure
  ansible.builtin.template:
    src: hd-idle
    dest: /etc/default/hd-idle
    mode: "0644"
  when: hdidle is defined
  notify:
    - restart hdidle
