- name: Configure smartmontools (defaults)
  template:
    src: smartmontools
    dest: /etc/default/smartmontools
  notify:
    - restart smartmontools

- name: Configure smartmontools (smartd.conf)
  template:
    src: smartd.conf
    dest: /etc/smartd.conf
  notify:
    - restart smartmontools

- name: Configure hd-idle (defaults)
  template:
    src: hd-idle
    dest: /etc/default/hd-idle
  notify:
    - restart hdidle