- name: Enable source repositories
  replace:
    path: /etc/apt/sources.list
    regexp: '^\s*#\s*(deb-src\s+.*)$'
    replace: '\1'

- name: Add docker repository key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg"

- name: Add docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_distribution_release }} stable"
    filename: "docker"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install default packages
  apt:
    name: "{{ packages_default_packages }}"
