- name: Add backports repository keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 04EE7237B7D453EC
    - 648ACFD622F3D138

- name: Add backports repository
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main

- name: Update apt cache
  apt:
    update_cache: yes

- name: Update all packages
  apt:
    name: "*"
    state: latest

- name: Install default packages
  apt:
    name: "{{ default_packages }}"




