- name: Create group
  group:
    name: "{{ fluentd_group }}"
    system: true

- name: Create user
  user:
    name: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    system: true

- name: Install ruby
  apt:
    name: [ "ruby", "ruby-dev" ]

- name: Install service
  gem:
    name: fluentd
    version: "{{ fluentd.version }}"
    user_install: no
  notify: restart

- name: Install plugins
  gem:
    name: "{{ item }}"
    user_install: no
    state: latest
  with_items:
    - "{{ fluentd.plugins }}"
  notify: restart

- name: Create config directory
  file:
    path: "{{ fluentd_conf_path }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0755

- name: Create log directory
  file:
    path: "{{ fluentd_log_path }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0755

- name: Configure
  template:
    src: "{{ fluentd_playbook_templates_path }}/fluent.conf.j2"
    dest: "{{ fluentd_conf_path }}/fluent.conf"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0644
  notify: restart fluentd

- name: Install service
  template:
    src: fluentd.service
    dest: /etc/systemd/system/fluentd.service
  notify:
    - restart

- name: Enable service
  systemd:
    name: fluentd
    enabled: yes
    masked: no
