- name: Check variables
  assert:
    that:
      - postfix.relay_host is defined
      - postfix.sasl_mail is defined
      - postfix.sasl_password is defined
    quiet: yes

- name: Install
  apt:
    name: [ "postfix", "libsasl2-modules" ]
    update_cache: yes

- name: Setup SASL password
  template:
    src: sasl_password
    dest: "{{ postfix_sasl_password_file }}"
    mode: "0640"
  notify:
    - postmap

- name: Change SASL permissions
  file:
    dest: "{{ postfix_sasl_password_dir }}"
    mode: "0640"
    recurse: yes

- name: Setup aliases
  lineinfile:
    dest: /etc/aliases
    regexp: "^root:"
    line: "root: {{ postfix.sasl_mail }}"
  notify:
    - aliases

- name: Configure
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
    mode: "0644"
  notify:
    - restart
