- name: Check variables
  ansible.builtin.assert:
    that:
      - postfix.relay_host is defined
      - postfix.sasl_mail is defined
      - postfix.sasl_password is defined
    quiet: yes

- name: Install
  ansible.builtin.apt:
    name: ["postfix", "libsasl2-modules"]
    update_cache: yes

- name: Setup SASL password
  ansible.builtin.template:
    src: sasl_password
    dest: "{{ postfix_sasl_password_file }}"
    mode: "0640"
  notify:
    - postmap

- name: Change SASL permissions
  ansible.builtin.file:
    dest: "{{ postfix_sasl_password_dir }}"
    mode: "0640"
    recurse: yes

- name: Setup aliases
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    regexp: "^root:"
    line: "root: {{ postfix.sasl_mail }}"
  notify:
    - aliases

- name: Configure
  ansible.builtin.template:
    src: main.cf
    dest: /etc/postfix/main.cf
    mode: "0644"
  notify:
    - restart postfix
