- name: Create AdGuard volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - adguard-conf
    - adguard-work

- name: Create AdGuard container
  community.docker.docker_container:
    name: adguard
    image: adguard/adguardhome:{{ adguard_version }}

    ports:
      - 53:53/tcp
      - 53:53/udp
    expose:
      - "{{ adguard_port }}:3000/tcp"

    volumes:
      - adguard-conf:/opt/adguardhome/conf
      - adguard-work:/opt/adguardhome/work

    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.rule: "Host(`{{ adguard_host }}.{{ domain_name }}`)"
      traefik.http.routers.adguard.service: "adguard"
      traefik.http.services.adguard.loadbalancer.server.port: "{{ adguard_port }}"

    networks:
      - name: "{{ docker_network_name }}"

    comparisons:
      labels: strict

    state: started
    restart_policy: unless-stopped
