- name: Install
  apt:
    name: smartmontools

- name: Configure defaults
  template:
    src: smartmontools
    dest: /etc/default/smartmontools
    mode: "0644"
  when: smartmontools is defined
  notify:
    - restart

- name: Configure smartd
  template:
    src: smartd.conf
    dest: /etc/smartd.conf
    mode: "0644"
  when: smartmontools is defined
  notify:
    - restart
