- name: Install
  ansible.builtin.apt:
    name: smartmontools

- name: Configure defaults
  ansible.builtin.template:
    src: smartmontools
    dest: /etc/default/smartmontools
    mode: "0644"
  when: smartmontools is defined
  notify:
    - restart smartmontools

- name: Configure smartd
  ansible.builtin.template:
    src: smartd.conf
    dest: /etc/smartd.conf
    mode: "0644"
  when: smartmontools is defined
  notify:
    - restart smartmontools
