---
- name: Install
  apt:
    name: [ "backupninja", "rdiff-backup", "hwinfo" ]
    update_cache: yes

- name: Create destination directory
  file:
    path: "{{ backup_dest_dir }}"
    mode: "0755"
    state: directory

- name: Create destination sub directories
  file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  with_items:
    - "{{ backup_dest_sys_dir }}"
    - "{{ backup_dest_rdiff_dir }}"

- name: Disable reporting success
  lineinfile:
    dest: "{{ backup_config_file }}"
    regexp: "^reportsuccess"
    line: "reportsuccess = no"

- name: Configure
  template:
    src: "{{ item }}"
    dest: "{{ backup_config_dir }}/{{ item | basename }}"
    mode: "0640"
  with_fileglob: "../templates/*"
