- name: Add apt key
  ansible.builtin.apt_key:
    url: https://dtcooper.github.io/raspotify/key.asc

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb https://dtcooper.github.io/raspotify raspotify main
    filename: "raspotify"

- name: Install
  ansible.builtin.apt:
    name: raspotify
    update_cache: yes

- name: Configure
  ansible.builtin.template:
    src: raspotify.conf
    dest: "{{ raspotify_config_file }}"
    mode: "0600"
  notify:
    - restart
