- name: Add apt key
  apt_key:
    url: https://dtcooper.github.io/raspotify/key.asc

- name: Add apt repository
  apt_repository:
    repo: deb [arch=armhf] https://dtcooper.github.io/raspotify raspotify main
    filename: 'raspotify'

- name: Install
  apt:
    name: raspotify
    update_cache: yes

- name: Configure
  template:
    src: raspotify.conf
    dest: "{{ raspotify_config_file }}"
    mode: "0600"
  notify:
    - restart
