- name: Add repository key
  ansible.builtin.apt_key:
    url: "https://azlux.fr/repo.gpg.key"

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb http://packages.azlux.fr/debian/ {{ ansible_distribution_release }} main"
    filename: "log2ram"

- name: Install
  ansible.builtin.apt:
    name: log2ram

- name: Configure
  ansible.builtin.template:
    src: log2ram.conf
    dest: /etc/log2ram.conf
    mode: "0644"
  when: log2ram is defined
  notify:
    - restart log2ram
