- name: Install
  apt:
    name: transmission-daemon
    update_cache: yes

- name: Create directories
  file:
    path: "{{ item }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: "0755"
    state: directory
  with_items:
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"

# Transmission override configuration on stop, grr
- name: Stop
  service:
    name: transmission-daemon
    state: stopped
  ignore_errors: true

- name: Configure
  template:
    src: settings.json
    dest: /etc/transmission-daemon/settings.json
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
  notify:
    - restart