- name: Install
  ansible.builtin.apt:
    name: transmission-daemon
    update_cache: yes

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: "0755"
    state: directory
  with_items:
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"

# Transmission override configuration on stop, grr
- name: Stop service before configuration
  ansible.builtin.service:
    name: transmission-daemon
    state: stopped

- name: Configure
  ansible.builtin.template:
    src: settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    mode: "0600"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
  notify:
    - restart

- name: Start
  ansible.builtin.service:
    name: transmission-daemon
    state: started
