- name: Create group
  ansible.builtin.group:
    name: "{{ viewtube_group }}"
    system: true

- name: Create user
  ansible.builtin.user:
    name: "{{ viewtube_user }}"
    ansible.builtin.group: "{{ viewtube_group }}"
    groups: ["docker"]
    system: true
  register: user

- name: Create directories
  ansible.builtin.file:
    path: "{{ user.home }}/{{ item }}"
    owner: "{{ viewtube_user }}"
    ansible.builtin.group: "{{ viewtube_group }}"
    mode: "0755"
    state: directory
  with_items:
    - conf
    - data

- name: Configure service
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ user.home }}/conf/docker-compose.yml"
    mode: "0644"
  notify:
    - restart

- name: Create containers
  community.docker.docker_compose:
    project_src: "{{ user.home }}/conf"

  notify:
    - restart

- name: Install service
  ansible.builtin.template:
    src: viewtube.service
    dest: /etc/systemd/system/viewtube.service
    mode: "0644"
  notify:
    - restart

- name: Enable service
  ansible.builtin.systemd:
    name: viewtube
    enabled: yes
  notify:
    - restart
