integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
    - basic_auth:
        password: "{{ grafana.password }}"
        username: "{{ grafana.username }}"
      url: "{{ grafana_prometheus_url }}"
prometheus:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: "{{ grafana.password }}"
            username: "{{ grafana.username }}"
          url: "{{ grafana_prometheus_url }}"
  wal_directory: /tmp/grafana-agent-wal
