- name: Check for binary
  stat:
    path: "{{ kodi_bin }}"
  register: kodi_bin_file

- name: Fail if Kodi is not installed
  fail:
    msg: Missing Kodi binary {{ kodi_bin }}
  when: not kodi_bin_file.stat.exists

- name: Create group
  group:
    name: "{{ kodi_group }}"
    system: true

- name: Create user
  user:
    name: "{{ kodi_user }}"
    group: "{{ kodi_group }}"
    groups: [ "audio", "input", "video", "render" ]
    system: true
  register: user

- name: Install service
  template:
    src: kodi.service
    dest: /etc/systemd/system/kodi.service
    mode: "0644"
  notify:
    - restart

- name: Check for initial configuration
  stat:
    path: "{{ user.home }}/.kodi"
  register: kodi_configuration_directory

- name: Create initial configuration
  systemd:
    name: kodi
    state: started
  when: not kodi_configuration_directory.stat.exists

- name: Create directories
  file:
    path: "{{ user.home }}/.kodi/{{ item }}"
    owner: "{{ kodi_user }}"
    group: "{{ kodi_group }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ kodi_userdata_dir }}"
    - "{{ kodi_subtitles_dir }}"

# Kodi override configuration on stop, grr
- name: Stop service before configuration
  systemd:
    name: kodi
    state: stopped

- name: Configure sources
  template:
    src: sources.xml.j2
    dest: "{{ user.home }}/.kodi/{{ kodi_userdata_dir }}/sources.xml"
    mode: "0644"

- name: Configure advanced settings
  template:
    src: advancedsettings.xml.j2
    dest: "{{ user.home }}/.kodi/{{ kodi_userdata_dir }}/advancedsettings.xml"
    mode: "0644"

- name: Configure guisettings.xml
  xml:
    file: "{{ user.home }}/.kodi/{{ kodi_userdata_dir }}/guisettings.xml"
    xpath: "/settings/setting[@id='{{ item.id }}']"
    value: "{{ item.value }}"
  with_items: "{{ kodi_gui_settings }}"

- name: Configure guisettings.xml (drop default attributes)
  xml:
    path: "/home/kodi/.kodi/{{ kodi_userdata_dir }}/guisettings.xml"
    xpath: "/settings/setting[@id='{{ item.id }}']/@default"
    state: absent
  with_items: "{{ kodi_gui_settings }}"

- name: Configure subtitles guisettings.xml
  xml:
    file: "{{ user.home }}/.kodi/{{ kodi_userdata_dir }}/guisettings.xml"
    xpath: "/settings/setting[@id='{{ item.id }}']"
    value: "{{ item.value }}"
  with_items: "{{ kodi_subtitles_gui_settings }}"

- name: Configure subtitles guisettings.xml (drop default attributes)
  xml:
    path: "/home/kodi/.kodi/{{ kodi_userdata_dir }}/guisettings.xml"
    xpath: "/settings/setting[@id='{{ item.id }}']/@default"
    state: absent
  with_items: "{{ kodi_subtitles_gui_settings }}"

- name: Start service after configuration
  systemd:
    name: kodi
    state: started
    enabled: yes
