---
- name: Create group
  group:
    name: "{{ kodi_group }}"
    system: true

- name: Create user
  user:
    name: "{{ kodi_user }}"
    group: "{{ kodi_group }}"
    groups: [ "audio", "input", "video" ]
    system: true
  register: user

- name: Install packages
  apt:
    name:
      - "kodi"
      - "kodi-audioencoder-flac"
      - "kodi-audioencoder-lame"
      - "kodi-audioencoder-vorbis"
      - "kodi-audioencoder-wav"
      - "kodi-imagedecoder-heif"
      - "kodi-imagedecoder-raw"
      - "kodi-inputstream-adaptive"
      - "kodi-inputstream-rtmp"
      - "kodi-peripheral-joystick"
    update_cache: yes

- name: Install service
  template:
    src: kodi.service
    dest: /etc/systemd/system/kodi.service
  notify:
    - restart

- name: Enable service
  systemd:
    name: kodi
    enabled: yes
    masked: no