---
- name: reboot
  reboot:
    post_reboot_delay: 10
    reboot_timeout: 60

- name: restart dhcpcd
  service:
    name: dhcpcd
    state: restarted

- name: restart journald
  service:
    name: systemd-journald
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart smartmontools
  service:
    name: smartmontools
    state: restarted

- name: restart hdidle
  service:
    name: hd-idle
    state: restarted

- name: restart log2ram
  service:
    name: log2ram
    state: restarted
