- name: Add apt key
  apt_key:
    url: https://apt.hyperion-project.org/hyperion.pub.key

- name: Add apt repository
  apt_repository:
    repo: "deb https://apt.hyperion-project.org/ {{ ansible_distribution_release }} main"
    filename: "hyperion"

- name: Install
  apt:
    name: hyperion
    update_cache: yes
