- name: Configure hostname '{{ hostname }}'
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Update hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ hostname }}'
  when: hostname is defined
