- name: Disable rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: stopped
    enabled: no

- name: Disable forwarding to syslog
  ansible.builtin.lineinfile:
    dest: "{{ common_journald_config_file }}"
    regexp: "^#?ForwardToSyslog="
    line: "ForwardToSyslog=no"
  when: journald is defined
  notify:
    - restart journald

- name: Limit journald size to '{{ journald.system_max_use }}'
  ansible.builtin.lineinfile:
    dest: "{{ common_journald_config_file }}"
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse={{ journald.system_max_use }}"
  when: journald is defined
  notify:
    - restart journald

- name: Limit journald retention to '{{ journald.max_file_sec }}'
  ansible.builtin.lineinfile:
    dest: "{{ common_journald_config_file }}"
    regexp: "^#?MaxFileSec="
    line: "MaxFileSec={{ journald.max_file_sec }}"
  when: journald is defined
  notify:
    - restart journald
