- name: Configure locale '{{ locale }}'
  community.general.locale_gen:
    name: "{{ locale }}"
  when: locale is defined

- name: Update 'LANG'
  ansible.builtin.command: localectl set-locale LANG={{ locale }}
  changed_when: locale != lookup('env', 'LANG')
