- import_tasks: boot.yml
  tags: [ "boot" ]
- import_tasks: swap.yml
  tags: [ "swap" ]
- import_tasks: hostname.yml
  tags: [ "hostname" ]
- import_tasks: locale.yml
  tags: [ "locale" ]
- import_tasks: timezone.yml
  tags: [ "timezone" ]
- import_tasks: security.yml
  tags: [ "security" ]
- import_tasks: dhcpcd.yml
  tags: [ "dhcpcd" ]
- import_tasks: journald.yml
  tags: [ "journald" ]
- import_tasks: rsyslog.yml
  tags: [ "rsyslog" ]
- import_tasks: hifiberry.yml
  tags: [ "hifiberry" ]
- import_tasks: mounts.yml
  tags: [ "mounts" ]
- import_tasks: motd.yml
  tags: [ "motd" ]
