- name: Set boot config params
  lineinfile:
    regexp: '^{{ item.name }}='
    line: "{{ item.name }}={{ item.value }}"
    path: "{{ boot_config_file }}"
  loop: "{{ boot_config_params }}"
  when: boot_config_params is defined
  notify:
    - reboot

- name: Enable boot config params
  lineinfile:
    regexp: '^#?{{ item }}'
    line: "{{ item }}"
    path: "{{ boot_config_file }}"
  loop: "{{ boot_config_enabled }}"
  when: boot_config_enabled is defined
  notify:
    - reboot

- name: Disable boot config params
  lineinfile:
    regexp: '^#?{{ item }}'
    line: "#{{ item }}"
    path: "{{ boot_config_file }}"
  loop: "{{ boot_config_disabled }}"
  when: boot_config_disabled is defined
  notify:
    - reboot

- name: Configure hostname
  hostname:
    name: "{{ hostname }}"

- name: Update hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ hostname }}'

- name: Configure locale
  locale_gen:
    name: "{{ locale }}"

- name: Update 'LANG'
  command: localectl set-locale LANG={{ locale }}
  changed_when: locale != lookup('env', 'LANG')

- name: Configure timezone
  timezone:
    name: "{{ timezone }}"

- name: Configure network
  template:
    src: dhcpcd.conf
    dest: "{{ dhcpcd_config_file }}"
  notify: restart dhcpcd

- name: Configure mount points
  mount:
    src: "UUID={{ item.uuid }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  with_items: "{{ mounts }}"
  when: mounts is defined

- name: Configure ALSA
  template:
    src: asound.conf
    dest: "{{ asound_config_file }}"

- name: Disable ubuntu login
  user:
    name: pi
    password: '!'

- name: Disable root login via SSH
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify:
    - restart sshd

- name: Disable password login via SSH
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify:
    - restart sshd

- name: Remove default motd
  file:
    path: /etc/motd
    state: absent

# https://github.com/gagle/raspberrypi-motd
- name: Configure custom motd
  copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
