- name: Set boot config params
  lineinfile:
    regexp: '^{{ item.name }}='
    line: "{{ item.name }}={{ item.value }}"
    path: "{{ boot_config_file }}"
    state: present
  loop: "{{ boot_config_params }}"
  notify:
    - reboot

- name: Enable boot config params
  lineinfile:
    regexp: '^#?{{ item }}'
    line: "{{ item }}"
    path: "{{ boot_config_file }}"
    state: present
  loop: "{{ boot_config_enabled }}"
  notify:
    - reboot

- name: Disable boot config params
  lineinfile:
    regexp: '^#?{{ item }}'
    line: "#{{ item }}"
    path: "{{ boot_config_file }}"
    state: present
  loop: "{{ boot_config_disabled }}"
  notify:
    - reboot

- name: Disable pi login
  user:
    name: pi
    password: '!'

- name: Disable root login via SSH
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - restart sshd

- name: Disable password login via SSH
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - restart sshd

- name: Disable last log
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "^PrintLastLog"
    line: "PrintLastLog no"
    state: present
  notify:
    - restart sshd

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    update_cache: yes

- name: Remove default motd
  file:
    path: /etc/motd
    state: absent

# https://github.com/gagle/raspberrypi-motd
- name: Configure custom motd
  copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh