- ansible.builtin.import_tasks: boot.yml
  tags: ["boot"]
- ansible.builtin.import_tasks: swap.yml
  tags: ["swap"]
- ansible.builtin.import_tasks: hostname.yml
  tags: ["hostname"]
- ansible.builtin.import_tasks: locale.yml
  tags: ["locale"]
- ansible.builtin.import_tasks: timezone.yml
  tags: ["timezone"]
- ansible.builtin.import_tasks: security.yml
  tags: ["security"]
- ansible.builtin.import_tasks: dhcpcd.yml
  tags: ["dhcpcd"]
- ansible.builtin.import_tasks: journald.yml
  tags: ["journald"]
- ansible.builtin.import_tasks: hifiberry.yml
  tags: ["hifiberry"]
- ansible.builtin.import_tasks: mounts.yml
  tags: ["mounts"]
- ansible.builtin.import_tasks: motd.yml
  tags: ["motd"]
- ansible.builtin.import_tasks: packages.yml
  tags: ["packages"]
