- name: Enable source repositories
  replace:
    path: /etc/apt/sources.list
    regexp: '^\s*#\s*(deb-src\s+.*)$'
    replace: '\1'

- name: Install default packages
  apt:
    name: "{{ packages }}"
