- name: Disable pi login
  user:
    name: pi
    password: "!"

- name: Disable root login via SSH
  lineinfile:
    dest: "{{ common_sshd_config_file }}"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify:
    - restart sshd

- name: Disable password login via SSH
  lineinfile:
    dest: "{{ common_sshd_config_file }}"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify:
    - restart sshd
