- name: Check for dphys-swapfile
  stat:
    path: /etc/dphys-swapfile
  register: dphys_swapfile

- name: Disable swap
  when:
    - dphys_swapfile.stat.exists
  block:
    - name: Turn off swap
      command: dphys-swapfile swapoff
        dphys-swapfile uninstall
    - name: Disable service
      systemd:
        name: dphys-swapfile
        state: stopped
        enabled: no
        masked: yes
