---
raspotify_config_file: /etc/default/raspotify
raspotify_volume_args: --enable-volume-normalisation --volume-ctrl linear --initial-volume {{ raspotify_initial_volume }}
raspotify_backend_args: --backend alsa --mixer=alsa --mixer-card {{ raspotify_alsa_device }} --device {{ raspotify_alsa_device }} --mixer-name {{ raspotify_alsa_mixer_name }}