- name: Add repository key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg"

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_distribution_release }} stable"
    filename: "docker"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    - python3-docker

- name: Create network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
