name: Ansible Lint

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v6
        with:
          targets: "*.yml"
