name: Ansible Lint

on:
  push: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v6
        with:
          path: "roles"
