- name: Install
  ansible.builtin.apt:
    name: aria2

- name: Create configuration directory
  ansible.builtin.file:
    path: /home/pi/.aria2
    owner: pi
    ansible.builtin.group: pi
    mode: "0755"
    state: directory

- name: Configure
  ansible.builtin.copy:
    src: aria2.conf
    dest: /home/pi/.aria2/aria2.conf
    owner: "pi"
    ansible.builtin.group: "pi"
    mode: "0644"
