- name: Install
  apt:
    name: aria2

- name: Create configuration directory
  file:
    path: /home/pi/.aria2
    owner: pi
    group: pi
    mode: "0755"
    state: directory

- name: Configure
  copy:
    src: aria2.conf
    dest: /home/pi/.aria2/aria2.conf
    owner: "pi"
    group: "pi"
    mode: "0644"
