---
- name: Create group
  group:
    name: "{{ pihole_group }}"
    system: true

- name: Create user
  user:
    name: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    groups: [ "docker" ]
    system: true
  register: user

- name: Create container
  docker_container:
    name: pihole
    image: pihole/pihole:{{ pihole_version }}
    published_ports:
      - 53:53/tcp
      - 53:53/udp
      - "{{ pihole_http_port }}:80"
      - "{{ pihole_https_port }}:443"
    volumes:
      - "{{ user.home }}/etc-pihole/:/etc/pihole/"
      - "{{ user.home }}/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    env:
      ServerIP: "{{ ansible_default_ipv4.address }}"
      PIHOLE_DNS: "{{ pihole_dns | join(';') }}"
      TZ: "{{ pihole_timezone }}"
      VIRTUAL_HOST: pi.hole
      PROXY_LOCATION: pi.hole
    container_default_behavior: no_defaults
    state: present
  notify:
    - restart

- name: Install service
  template:
    src: pihole.service.j2
    dest: /etc/systemd/system/pihole.service
  notify:
    - restart



